name: container CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{github.run_number}}
    - name: Build latest
      run: docker build . --file Dockerfile --tag my-image-name
    - name: Login to docker hub
      run: docker login -u ${{secrets.REGISTRY_USERNAME}} -P ${{secrets.REGISTRY_PASS}}
    - name: tag image
      run: docker tag my-image-name:${{github.run_number}} ${{secrets.REGISTRY_USERNAME}}/my-image-name:${{github.run_number}}
    - name: docker push
      run: docker push ${{secrets.REGISTRY_USERNAME}}/my-image-name:${{github.run_number}}